In [2]:
import numpy as np

np

<module 'numpy' from 'c:\\Projetos\\ML-zoomcamp\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.0)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
print(np.arange(11))
print(np.arange(2, 11))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]


In [7]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
n = np.array(([1,2,3],
              [4,5,6],
              [7,8,9]))


In [9]:
n[1][1] = 20

In [10]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [11]:
n[2] = [1,1,1]
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 1,  1,  1]])

In [12]:
n[:, 1]

array([ 2, 20,  1])

In [13]:
np.random.seed(123)
np.random.rand(5,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752]])

# Elemente-wise operations

In [14]:
n1 = np.arange(5)
n1

array([0, 1, 2, 3, 4])

In [16]:
n1 * 2

array([0, 2, 4, 6, 8])

In [17]:
n3 = n1 * 100
n3

array([  0, 100, 200, 300, 400])

In [18]:
n3.mean()

np.float64(200.0)

In [19]:
n3.std()

np.float64(141.4213562373095)

In [21]:
print(n1.sum())
print(n3.sum())

10
1000
